### ISSUE TITLE
Bloch sphere looks the same after 180 degree turns

### ISSUE THREAD

**Issue by ThoAppelsin** [cduck/bloch_sphere#1]
See the X gate visualization. The animation is fine, but the sphere looks just the same as it was after it, making it hard to compare against the original state.

A solution to this could be making two halves of the axial bands darker/brighter, e.g. the +z half of the x-band (band that is perpendicular to x-axis) dark green and the -z half bright. However, the choice of split will be arbitrary (i.e. why not make it +/- y, instead of z?) which might be a reason not to solve this issue like this.

A marker could be placed on the band, but its position will again be arbitrary.

**Comment by cduck** [comment]
I agree it could be more visually clear.  A less arbitrary choice could be to make the three ¼ arcs between the +X, +Y, and +Z lighter/darker.

Is this a change you would like to contribute?  I can link to the relevant lines of code.

**Comment by ThoAppelsin** [comment]
I have made some changes to [`draw_band`](https://github.com/cduck/bloch_sphere/blob/a7fe0d14c08d88bae72aaba9117999636d80aa34/bloch_sphere/animate_bloch.py#L201). It now expects its `color` parameter to be a list of color specifiers. It then draws the quarter arcs by those colors.

If `color` has less than `divs` elements, it is replicated until there are `divs`-many elements.

If `color` is not a list, it is assumed to be a singular color specifier, which it repeats `divs`-many times.

The end result is as follows (I also changed the original blue to be lighter):

![hadamard](https://user-images.githubusercontent.com/6666524/109712071-9c334b80-7bb0-11eb-92b3-059c907a167c.gif)

I don't know why I don't get the arrow heads with this as in the gifs in the README.

**Comment by cduck** [comment]
Nice.  It may be more clear if only one segment is dark instead of two.  Go ahead and open a pull request.

Regarding the arrows, what do you get if you run the arrow example in https://github.com/cduck/drawSvg/#basic-drawing-elements and view `d.rasterize('output.png')`?  Maybe it's a Cairo version issue.

**Comment by ThoAppelsin** [comment]
Done. It is indeed clearer with just one dark segment. Pull request is here: #2 

I think coloring a segment has made the animations are easier to follow and the overall difference from the initial state more noticeable. However, I also think it looks a bit cluttered with so many colors and that it sure looks cleaner when all the segments on a plane are the same color. The decision is yours.

As for the arrows; I ran the script in the link via Python (I don't have Jupyter) and checked out the output files. While the `example.svg` does have the arrows heads, the `example.png` does not. I have `cairo@1.16.0` obtained via Homebrew, and the following is what I get from from `pip freeze`:

```
cairocffi==1.2.0
CairoSVG==2.5.1
cffi==1.14.5
cssselect2==0.4.1
defusedxml==0.6.0
drawSvg==1.8.1
hyperbolic==1.3.1
imageio==2.9.0
numpy==1.20.1
Pillow==8.1.1
pycparser==2.20
tinycss2==1.1.0
webencodings==0.5.1
```

**Comment by cduck** [comment]
OK.  I'll check my Cairo version tomorrow.  Can you open a separate issue to track this?

Some alternative ideas to adding colors that may be cleaner:
- Make those ¼-segments wider (extend further toward the origin)
- Add a think black ¼-arc line on the edge of each.

**Comment by ThoAppelsin** [comment]
Sorry, I felt like I should get my hands dirty for the recommendation I offered myself, but these further tweaks/fixes are beyond my interest. I did open the issue to your convenience: https://github.com/cduck/drawSvg/issues/37

**Comment by cduck** [comment]
Thanks for contributing.  I totally understand.  I may try those ideas if I have some time.  For now, I'll merge your PR and re-render the examples.
