### ISSUE TITLE
Use Colored axis instead to illustrate the rotation

### ISSUE THREAD

**Issue by BichengYing** [cduck/bloch_sphere#3]
The illustration example in the readme is very impressive. However, I feel the x, y, z ring is a little bit overwhelming to me. 
I am NOT suggesting not to showing the ring. But I suggest can we have another mode that only showing the rotation effect on the axis, i.e. like show original +x, +y, +z axes in bold blue, red, green only.

I think colored axis can be useful. For example, for all 24 single qubit Clifford gates, they just permute the axis. Showing the axis only can be very clean and informative. Related to https://github.com/quantumlib/Cirq/pull/4050 that connecting the clifford gate to phased xz gate. Also related to visualize the `decompose_rotation` that you wrote there.

**Comment by cduck** [comment]
I agree clarity could be improved.  If you want to try out alternative designs or hiding the outer rings [these lines of code](https://github.com/cduck/bloch_sphere/blob/04ba064a8d319aa838ba949247269c8416126117/bloch_sphere/animate_bloch.py#L263) are where the outer rings are drawn.  The inner arrows are drawn [here](https://github.com/cduck/bloch_sphere/blob/04ba064a8d319aa838ba949247269c8416126117/bloch_sphere/animate_bloch.py#L292) and the outer arrows [here](https://github.com/cduck/bloch_sphere/blob/04ba064a8d319aa838ba949247269c8416126117/bloch_sphere/animate_bloch.py#L309).

I think it is reasonable to add a command line argument to control the visual look of the spheres.  Feel free to open a pull request if you want feedback on any designs you try out.

**Comment by BichengYing** [comment]
I did some tests. The demo looks like this
![Example output animation](https://raw.githubusercontent.com/ybc1991/bloch_sphere/test_arrow_style/examples/xy_vs_z.gif)

What do you think about it? Any suggestion to improve it?

**Comment by cduck** [comment]
It looks OK.  It's definitely less overwhelming.  You can also change the colors of the arrow heads (duplicate [this line](https://github.com/cduck/bloch_sphere/blob/04ba064a8d319aa838ba949247269c8416126117/bloch_sphere/animate_bloch.py#L290) for each color).  You can also try simplifying the colors on the outer sphere and/or try enabling the [elevation lines](https://github.com/cduck/bloch_sphere/blob/04ba064a8d319aa838ba949247269c8416126117/bloch_sphere/animate_bloch.py#L290) so the focus is on the arrows.

**Comment by BichengYing** [comment]
Thanks, update the color of arrow head.
![Example output animation](https://raw.githubusercontent.com/ybc1991/bloch_sphere/test_arrow_style/examples/face_clifford_vs_phased_xz.gif)

I also tried the elevation lines only. Personally, I think it is ok but the outer band looks more fancy :)
![Example output animation](https://raw.githubusercontent.com/ybc1991/bloch_sphere/test_arrow_style/examples/face_clifford_elevation_line.gif)

What do you think?

**Comment by cduck** [comment]
The arrows look better.  I also don't like the elevation lines on the inner sphere.  I was thinking of the elevation lines on the outer sphere, more like https://qiskit.org/textbook/ch-labs/image/L7_bloch_sphere.png but that would require modifying the sequence and width of the rings.

The way you have now (in the first image in your last comment) looks good enough to add as an option if you want to open a pull request.
